### PR TITLE
merge with official tado 0.2.0 

### PR DESCRIPTION
**Pull request by LutzHelling**

### CODE REVIEW

**Comment by DutchmanNL** [comment]
I think you try to merge my repo with yours ? Than the pull should be other side around :)

**Comment by LutzHelling** [comment]
yes, you are right. Sorry, I try to revert the request.

Thank yout.

Cheers
Lutz

------ Originalnachricht ------
Von: "Dutchman" <notifications@github.com>
An: "iobroker-community-adapters/ioBroker.tado" 
<ioBroker.tado@noreply.github.com>
Cc: "LutzHelling" <lutz@helling-online.com>; "Author" 
<author@noreply.github.com>
Gesendet: 29.08.2020 18:11:52
Betreff: Re: [iobroker-community-adapters/ioBroker.tado] merge with 
official tado 0.2.0 (#39)

**Comment by DutchmanNL** [comment]
no problem I will close the pull :)
If your source is equal, you could also just do a new fork bu I need to check as I saw something in your pull related to wifi which I didn't have yet I think 🗡️

**Comment by LutzHelling** [comment]
ok, fine. Thank you so far for your good work with this adapter!

Cheers!

------ Originalnachricht ------
Von: "Dutchman" <notifications@github.com>
An: "iobroker-community-adapters/ioBroker.tado" 
<ioBroker.tado@noreply.github.com>
Cc: "LutzHelling" <lutz@helling-online.com>; "Author" 
<author@noreply.github.com>
Gesendet: 29.08.2020 18:14:12
Betreff: Re: [iobroker-community-adapters/ioBroker.tado] merge with 
official tado 0.2.0 (#39)

**Comment by DutchmanNL** [comment]
Hey @LutzHelling, i compared our source and found some additions. Based on "cherry picking" I separated your commits and included it in 0.2.0-beta.1 and updated the contributor / readme with your additions

Thank you !

https://github.com/iobroker-community-adapters/ioBroker.tado/commit/329ea5feb5ea2fe85209f7c5159573d3a29fd12e

**Pull request closed without merging**
