### PR TITLE
update NodeJS-versions

### PR DESCRIPTION
**Pull request by HGlab01**

### CODE REVIEW

**Comment by DutchmanNL** [comment]
node 14 is no yet fully ready for testing, .travis.yml is for automated testing only no relation to installation

**Comment by HGlab01** [comment]
Hi @DutchmanNL!
Main reason to adjust Travis configuration was, that recent jscontroller does no longer work with nodejs v8. Therefore I updated in my fork to 10,12,14 instead of 8,10,12 to be able to execute Travis again.

**Comment by DutchmanNL** [comment]
Which is Fine ☺️ I will Remove node 8 for all my adapters by next week and check the status of node 14 testing.
Not sure if our testing automation is fully ready for 14.

Will give an update here with the outcome

Thank you providing feedback, appreciated !
PS : Testing must be Updates in travis and github actions 😉, we move more and more to github actions allowing automated deployment 

I will reopen this pull as reminder of node 8 removal and 14 addition

**Comment by DutchmanNL** [comment]
node 8 removed and 14 successfully implemented, you can have a look at https://github.com/iobroker-community-adapters/ioBroker.tado/commit/dead74908230514dd94fd8b6d412c4bda8fcf8d8 to see how Travis & GitHub Actions are configured

**Pull request closed without merging**
